RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at new NodeError (node:internal/errors:278:15)
    at Socket.onChildStdout (node:child_process:409:14)
    at Socket.emit (node:events:376:20)
    at addChunk (node:internal/streams/readable:311:12)
    at readableAddChunk (node:internal/streams/readable:282:11)
    at Socket.Readable.push (node:internal/streams/readable:225:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:192:23)TypeError: fs.createWriteStream is not a function
    at imageGetHandler (file:///Users/Diatta/WebstormProjects/photagallery/src/api/image/image_routes.mjs:69:28)
    at dispatch (/Users/Diatta/WebstormProjects/photagallery/node_modules/koa-compose/index.js:42:32)
    at validateParams (file:///Users/Diatta/WebstormProjects/photagallery/src/utils/koa-utilities.mjs:15:15)
    at dispatch (/Users/Diatta/WebstormProjects/photagallery/node_modules/koa-compose/index.js:42:32)
    at /Users/Diatta/WebstormProjects/photagallery/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/Diatta/WebstormProjects/photagallery/node_modules/koa-compose/index.js:42:32)
    at /Users/Diatta/WebstormProjects/photagallery/node_modules/@koa/router/lib/router.js:372:16
    at dispatch (/Users/Diatta/WebstormProjects/photagallery/node_modules/koa-compose/index.js:42:32)
    at /Users/Diatta/WebstormProjects/photagallery/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/Diatta/WebstormProjects/photagallery/node_modules/@koa/router/lib/router.js:377:31)TypeError: stream.pipe is not a function
    at imageGetHandler (file:///Users/Diatta/WebstormProjects/photagallery/src/api/image/image_routes.mjs:71:12)
    at dispatch (/Users/Diatta/WebstormProjects/photagallery/node_modules/koa-compose/index.js:42:32)
    at validateParams (file:///Users/Diatta/WebstormProjects/photagallery/src/utils/koa-utilities.mjs:15:15)
    at dispatch (/Users/Diatta/WebstormProjects/photagallery/node_modules/koa-compose/index.js:42:32)
    at /Users/Diatta/WebstormProjects/photagallery/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/Diatta/WebstormProjects/photagallery/node_modules/koa-compose/index.js:42:32)
    at /Users/Diatta/WebstormProjects/photagallery/node_modules/@koa/router/lib/router.js:372:16
    at dispatch (/Users/Diatta/WebstormProjects/photagallery/node_modules/koa-compose/index.js:42:32)
    at /Users/Diatta/WebstormProjects/photagallery/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/Diatta/WebstormProjects/photagallery/node_modules/@koa/router/lib/router.js:377:31)Error: This socket has been ended by the other party
    at PromiseConnection.query (/Users/Diatta/WebstormProjects/photagallery/node_modules/mysql2/promise.js:92:22)
    at imageIdExists (file:///Users/Diatta/WebstormProjects/photagallery/src/utils/sql-utils.mjs:15:30)
    at addImageMetadata (file:///Users/Diatta/WebstormProjects/photagallery/src/utils/sql-utils.mjs:21:17)
    at imagePostHandler (file:///Users/Diatta/WebstormProjects/photagallery/src/api/image/image_routes.mjs:40:26)
    at async file:///Users/Diatta/WebstormProjects/photagallery/src/server.mjs:28:9
    at async serve (/Users/Diatta/WebstormProjects/photagallery/node_modules/koa-static/index.js:53:9)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/hqOvUgdGUbqiDyYs_low s3://waiting_on_bug_bucket
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/hqOvUgdGUbqiDyYs_low to s3://waiting_on_bug_bucket/hqOvUgdGUbqiDyYs_low Could not connect to the endpoint URL: "http://localhost:8333/waiting_on_bug_bucket/hqOvUgdGUbqiDyYs_low"

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/RmOVHeVYruzGXfBR_med s3://photagallery_medium_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/RmOVHeVYruzGXfBR_med to s3://photagallery_medium_res/RmOVHeVYruzGXfBR_med An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/eOnYrnljDijxetyR_med s3://photagallery_medium_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/eOnYrnljDijxetyR_med to s3://photagallery_medium_res/eOnYrnljDijxetyR_med An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/upload_57f20da67c9bdd49ffb00bc1ca214666 s3://photagallery_full_res

The user-provided path /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/upload_57f20da67c9bdd49ffb00bc1ca214666 does not exist.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/upload_6598cfe50c7a87c885e839a1aef01a57 s3://photagallery_full_res

The user-provided path /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/upload_6598cfe50c7a87c885e839a1aef01a57 does not exist.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/hNACrztAvezFABPU_low s3://photagallery_low_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/hNACrztAvezFABPU_low to s3://photagallery_low_res/hNACrztAvezFABPU_low Could not connect to the endpoint URL: "http://localhost:8333/photagallery_low_res/hNACrztAvezFABPU_low"

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/VXNcgxQkCVFCRgxm_full s3://photagallery_full_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/VXNcgxQkCVFCRgxm_full to s3://photagallery_full_res/VXNcgxQkCVFCRgxm_full An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/BbdKfDMEMrrhhSQH_low s3://photagallery_low_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/BbdKfDMEMrrhhSQH_low to s3://photagallery_low_res/BbdKfDMEMrrhhSQH_low Could not connect to the endpoint URL: "http://localhost:8333/photagallery_low_res/BbdKfDMEMrrhhSQH_low"

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/DEvNKQERpSpJBOSW_med s3://photagallery_medium_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/DEvNKQERpSpJBOSW_med to s3://photagallery_medium_res/DEvNKQERpSpJBOSW_med Could not connect to the endpoint URL: "http://localhost:8333/photagallery_medium_res/DEvNKQERpSpJBOSW_med"

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/TlSWsxqGiZfyblUx_full s3://photagallery_full_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/TlSWsxqGiZfyblUx_full to s3://photagallery_full_res/TlSWsxqGiZfyblUx_full Could not connect to the endpoint URL: "http://localhost:8333/photagallery_full_res/TlSWsxqGiZfyblUx_full"

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/zglOzUbiXMudZQuL_full s3://photagallery_full_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/zglOzUbiXMudZQuL_full to s3://photagallery_full_res/zglOzUbiXMudZQuL_full An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/JuAdEQJYoMEJNmNt_med s3://photagallery_medium_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/JuAdEQJYoMEJNmNt_med to s3://photagallery_medium_res/JuAdEQJYoMEJNmNt_med An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/MQWQPgPNlnvJoLNB_med s3://photagallery_medium_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/MQWQPgPNlnvJoLNB_med to s3://photagallery_medium_res/MQWQPgPNlnvJoLNB_med An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/iLDJKEHXPhQbEwBg_med s3://photagallery_medium_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/iLDJKEHXPhQbEwBg_med to s3://photagallery_medium_res/iLDJKEHXPhQbEwBg_med An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/vZNrTwLDELDnSnhV_med s3://photagallery_medium_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/vZNrTwLDELDnSnhV_med to s3://photagallery_medium_res/vZNrTwLDELDnSnhV_med An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/pTClviISMEFfcXUJ_med s3://photagallery_medium_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/pTClviISMEFfcXUJ_med to s3://photagallery_medium_res/pTClviISMEFfcXUJ_med An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/GLfgHCihMFrijxLg_med s3://photagallery_medium_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/GLfgHCihMFrijxLg_med to s3://photagallery_medium_res/GLfgHCihMFrijxLg_med An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/mqmWOMhkdpgbfcFu_med s3://photagallery_medium_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/mqmWOMhkdpgbfcFu_med to s3://photagallery_medium_res/mqmWOMhkdpgbfcFu_med An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/ZvYAunQCplRtrTee_full s3://photagallery_full_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/ZvYAunQCplRtrTee_full to s3://photagallery_full_res/ZvYAunQCplRtrTee_full An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp /var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/YrcMPgSyDyHRPNCI_full s3://photagallery_full_res
upload failed: ../../../../var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/YrcMPgSyDyHRPNCI_full to s3://photagallery_full_res/YrcMPgSyDyHRPNCI_full An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp soVrXQDbvSSINmod s3://photagallery_low_res

The user-provided path soVrXQDbvSSINmod does not exist.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp GqKvpgyuGqBXqEjT s3://photagallery_low_res

The user-provided path GqKvpgyuGqBXqEjT does not exist.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp nDHZktUOkXWfNzNd s3://photagallery_low_res

The user-provided path nDHZktUOkXWfNzNd does not exist.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)Error: ENOENT: no such file or directory, open '/var/folders/r0/ktfq_wg90b18mrfb034n78wr0000gn/T/low/jZguXeGOwomIQtUh'Error: Command failed: aws --endpoint-url http://localhost:8333 s3 cp aqInEnzgwwLjvABp s3://photagallery_low_res

The user-provided path aqInEnzgwwLjvABp does not exist.

    at ChildProcess.exithandler (node:child_process:333:12)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)